
# Tasks: SimpleSAMLphp
#
# Author: Remko van den Hoef
# File: tasks/mail.yml
#


- name: "Install packages"
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
    - zip
    - unzip
    - git
    - apache2
    - curl
    - php7.2
    - php7.2-common
    - php7.2-date
    - php7.2-dom
    - php7.2-hash
    - php7.2-libxml
    - php7.2-openssl
    - php7.2-pcre
    - php7.2-SPL
    - php7.2-zlib
    - php7.2-json
    - php7.2-mbstring
    - php7.2-cURL
    - php7.2-ldap
    - php7.2-radius
    - php7.2-session
    - php7.2-memcache

- name: Download and unzip package
  unarchive:
    src: https://simplesamlphp.org/download?latest
    dest: /var/simplesamlphp
    remote_src: yes


- name: Transfer apache2 config
  template:
    src: simplesamlphp.conf.j2
    dest: /etc/apache2/sites-available/simplesamlphp.conf
    owner: bin
    group: wheel
    mode: '0644'

- name: Apache symbolic link
  raw: ln -s /etc/apache2/sites-available/simplesamlphp.conf /etc/apache2/sites-enabled/

- name: Update SimpleSAMLphp config
  ansible.builtin.lineinfile:
    path: /var/simplesamlphp/config-templates/config.php
    regexp: 'baseurlpath' =>
    line:    'baseurlpath' => 'https://{{ baseurl }}/simplesaml/',

- name: Update SimpleSAMLphp config
  ansible.builtin.lineinfile:
    path: /var/simplesamlphp/config-templates/config.php
    regexp: 'auth.adminpassword' =>
    line:    'auth.adminpassword' => '{{ authadmin }}',

- name: Update SimpleSAMLphp config
  ansible.builtin.lineinfile:
    path: /var/simplesamlphp/config-templates/config.php
    regexp: 'secretsalt' =>
    line:    'secretsalt' => '{{  secretsalt }}',

- name: Update SimpleSAMLphp config
  ansible.builtin.lineinfile:
    path: /var/simplesamlphp/config-templates/config.php
    regexp: 'technicalcontact_email' =>
    line:    'technicalcontact_email' => '{{ contactmail }}',

- name: Update SimpleSAMLphp config
  ansible.builtin.lineinfile:
    path: /var/simplesamlphp/config-templates/config.php
    regexp: 'timezone' =>
    line:    'timezone' => 'Europe/Amsterdam',

    
